# Hostname to bind the server to (default none) 
hostname: 
# Port to bind the server to (default 4040)
port: "4040"
notification:
  service: discord
  url: <URL>
sources:
- end_point: filtered_calender
  heartbeat: 60
  xwr_name: My Merged Calender
  info:
    - name: Personal
      url: <URL>
      rules:
        - name: Vacation
          component: LOCATION
          check: EQUALS 
          data: 
            - Japan
            - Zambia
            - Belgium
        - name: Kids
          component: SUMMARY
          check: CONTAINS
          data:
            - Food
            - Hobbies
    - name: Work
      url: <URL2>
      modifiers:
        - name: Work starting soon # Used as alarm nam
          action: ALARM
          data: "-PT60M" # one hour
          rules:
              - check: "FIRST_OF_DAY"

- end_point: full_calender
  heartbeat: 30
  xwr_name: My Full Calender
  info:
    - name: Personal
      url: <URL>
    - name: Work
      url: <URL>