name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: 🧹 Lint
        uses: golangci/golangci-lint-action@v6

      - name: 🧪 Test
        run: go test -v ./...